[project]
name = "dsia-26-27-agusti-carlos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "carlosagustii", email = "carlosacanga03@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.6",
    "pydantic>=2.13.5",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[tool.uv]
